export const FOOTER_CONTENT_HEIGHT = 84
export const FOOTER_BOTTOM_TAIL = 42
export const FOOTER_PANEL_HEIGHT = FOOTER_CONTENT_HEIGHT + FOOTER_BOTTOM_TAIL
export const FOOTER_PIPELINE_HEIGHT = 50
export const BOTTOM_HUD_HEIGHT = FOOTER_PANEL_HEIGHT + FOOTER_PIPELINE_HEIGHT
export const TOUCH_CONTROLS_BOTTOM = BOTTOM_HUD_HEIGHT + 18
export const WAVE_BOTTOM_PADDING = BOTTOM_HUD_HEIGHT + 84
